# Default values for ravivecho.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/sublime-seat-330313/ravivecho@sha256:a44b19a2c974063127af17675e2274424582a4a577ea5a8c0b64163bf55f4059
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


## set configmap env variables for mongo
configmap:
  port: "3000"
  loglevel: "info"
  persist: "true"
  mongodburl: "mongodb://raviv:abb123@mongoecho-mongodb-0.mongoecho-mongodb-headless:27017,mongoecho-mongodb-1:27017/echodb"
  dbname: "echodb"

deploylabel:
  name: "echoapp"

configlabel:
  name: "echo-config"
  
servicelabel:
  name: "echoapp-service"

secret:
  uri: "mongodb://raviv:abb123@mongoecho-mongodb-0.mongoecho-mongodb-headless:27017,mongoecho-mongodb-1:27017/echodb"
secret:
  uri: "mongodb://raviv:abb123@mongoecho-mongodb-0.mongoecho-mongodb-headless:27017,mongoecho-mongodb-1:27017/echodb"

